services:
  - type: web
    name: halo-app
    env: node
    region: oregon
    plan: free
    buildCommand: |
      cd frontend && npm install && npm run build &&
      cd ../backend && npm install && npm run build
    startCommand: node dist/index.js
    rootDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: halo-db
          property: connectionString

databases:
  - name: halodb
    plan: free
